language: node_js

node_js: stable

cache:
    apt: true
    directories:
        - node_modules

before_install:
    - export TZ='Asia/Shanghai'
    - chmod +x ./gh-pages.sh

install:
    - npm install
    - wget https://github.com/gohugoio/hugo/releases/download/v0.64.0/hugo_extended_0.64.0_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb

script:
    - npm run build

after_script:
    - ./gh-pages.sh

branches:
    only:
        - master

env:
    global:
        - GH_REF: github.com/guanqr/guanqr.github.io.git