[build]
  base = "/"
  publish = "public/"
  command = "npm run build"

[context.production]
  command = "npm run build && npm run ipfs-deploy"

[build.environment]
  HUGO_VERSION = "0.71.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://guanqr.netlify.com/*"
  to = "https://guanqr.com/:splat"
  status = 301
  force = true

#[[redirects]]	
#  from = "https://www.guanqr.com/*"	
#  to = "https://guanqr.com/:splat"	
#  status = 301	
#  force = true

#[[redirects]]	
#  from = "https://blog.guanqr.com/*"	
#  to = "https://guanqr.com/:splat"	
#  status = 301	
#  force = true