[context.production.environment]
  HUGO_VERSION = "0.63.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[build]
  base = "/"
  publish = "public/"
  command = "npm run build"
  # command = "npm run build && npm run ipfs-deploy"

[[redirects]]
  from = "https://guanqr.netlify.com/*"
  to = "https://guanqr.com/:splat"
  status = 301
  force = true

[[redirects]]	
  from = "https://www.guanqr.com/*"	
  to = "https://guanqr.com/:splat"	
  status = 301	
  force = true

[[redirects]]	
  from = "https://blog.guanqr.com/*"	
  to = "https://guanqr.com/:splat"	
  status = 301	
  force = true