[context.production.environment]
HUGO_VERSION = "0.59.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[build]
  base = "/"
  publish = "public/"
  command = "hugo && gulp build && gulp"

[[redirects]]
  from = "https://guanqr-blog.netlify.com/*"
  to = "https://blog.guanqr.com/:splat"
  status = 301
  force = true