[context.production.environment]
  HUGO_VERSION = "0.62.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[build]
  base = "/"
  publish = "public/"
  command = "npm run build && npm run ipfs-deploy"

[[redirects]]
  from = "https://guanqr.netlify.com/*"
  to = "https://blog.guanqr.com/:splat"
  status = 301
  force = true