[build]
  base = "/"
  publish = "public/"
  command = "npm run build"

[build.environment]
  HUGO_VERSION = "0.74.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://guanqr.netlify.app/*"
  to = "https://guanqr.com/:splat"
  status = 301
  force = true