name: build

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      SOURCE_REPO: guanqr/blog              # 博客源码仓库
      DEPLOY_REPO: guanqr/guanqr.github.io  # 博客部署仓库
      DEPLOY_BRANCH: master                 # 博客部署分支
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

    steps:
    - name: 'Checkout source'
      uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15.4.0'

    - name: Install dependencies
      run: npm install

    - name: 'Building...'
      uses: ./.github/actions/hugo-deploy
