name: build

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    env:
      TZ: Asia/Shanghai
      SOURCE_REPO: guanqr/blog              # 博客源码仓库
      DEPLOY_REPO: guanqr/guanqr.github.io  # 博客部署仓库
      DEPLOY_BRANCH: master                 # 博客部署分支
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.16.0'

    - name: Install dependencies
      run: npm install

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.82.0'
        extended: true

    - name: Build
      run: npm run build

    - name: Deploy
      run: |
        cd public && git init
        git add .
        git commit -m "Automated Deployment By GitHub Actions @ $(date '+%Y-%m-%d %H:%M:%S') ${TZ}"
        git push --force "https://$DEPLOY_KEY@github.com/$DEPLOY_REPO" master:$DEPLOY_BRANCH